"""
Database Migration: Add Analytics Fields to Distributors
Run this after: flask db migrate -m "Add analytics fields to distributors"
"""

# Migration will be auto-generated by Flask-Migrate
# This file is for reference only

# New fields added to Distributor model:
# - loyalty_points (Integer, default=0)
# - customer_satisfaction_score (Integer, default=5)
# - average_order_value (Float, default=0.0)
# - total_lifetime_value (Float, default=0.0)
# - last_order_date (Date, nullable=True)
# - order_frequency (String(32), default='monthly')

# To apply migration:
# 1. cd mohierp/mohi-erp
# 2. flask db migrate -m "Add analytics fields to distributors"
# 3. flask db upgrade
