"""Add theme settings tables

Revision ID: 4d600ea50fdd
Revises: d31109bc00e1
Create Date: 2026-02-01 00:04:20.751307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d600ea50fdd'
down_revision = 'd31109bc00e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_setting_key'), ['setting_key'], unique=True)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'setting_key', name='_user_setting_uc')
    )
    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_of_accounts_account_code'))

    op.drop_table('chart_of_accounts')
    op.drop_table('financial_years')
    with op.batch_alter_table('accounting_entries', schema=None) as batch_op:
        batch_op.alter_column('reference_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('account_head',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
        batch_op.alter_column('credit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_accounting_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.drop_constraint(batch_op.f('accounting_entries_journal_id_fkey'), type_='foreignkey')
        batch_op.drop_column('journal_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('expense_number',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total_gst',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
        batch_op.alter_column('cgst_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
        batch_op.alter_column('sgst_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
        batch_op.alter_column('igst_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
        batch_op.alter_column('vendor_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('invoice_number',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('payment_mode',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('reference_number',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('expense_category',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('approval_status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_expenses_expense_date'), ['expense_date'], unique=False)
        batch_op.drop_column('attachment_path')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reference_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reference_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('user_remark', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reference_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reference_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('entry_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_journal_entries_journal_number'))
        batch_op.create_index(batch_op.f('ix_journal_entries_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_number'), ['entry_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_journal_entries_status'), ['status'], unique=False)
        batch_op.drop_constraint(batch_op.f('journal_entries_created_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('journal_entries_approved_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['submitted_by_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('entry_date')
        batch_op.drop_column('journal_number')
        batch_op.drop_column('narration')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('created_by')
        batch_op.drop_column('approved_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approval_status', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('narration', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('journal_number', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('journal_entries_approved_by_fkey'), 'users', ['approved_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('journal_entries_created_by_fkey'), 'users', ['created_by'], ['id'])
        batch_op.drop_index(batch_op.f('ix_journal_entries_status'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_number'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_date'))
        batch_op.create_index(batch_op.f('ix_journal_entries_journal_number'), ['journal_number'], unique=True)
        batch_op.alter_column('entry_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('submitted_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('reference_id')
        batch_op.drop_column('reference_type')
        batch_op.drop_column('user_remark')
        batch_op.drop_column('reference_date')
        batch_op.drop_column('reference_number')
        batch_op.drop_column('status')
        batch_op.drop_column('date')
        batch_op.drop_column('entry_number')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_path', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_expenses_expense_date'))
        batch_op.alter_column('approval_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('expense_category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('reference_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('payment_mode',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('invoice_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('vendor_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('igst_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('sgst_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('cgst_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('total_gst',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('expense_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('accounting_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('accounting_entries_journal_id_fkey'), 'journal_entries', ['journal_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_accounting_entries_entry_date'))
        batch_op.alter_column('credit',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('debit',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('account_head',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('reference_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    op.create_table('financial_years',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_closed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('financial_years_pkey')),
    sa.UniqueConstraint('year_name', name=op.f('financial_years_year_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('chart_of_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('account_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('account_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('account_group', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('opening_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_gst_applicable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('gst_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], name=op.f('chart_of_accounts_parent_id_fkey_fixed')),
    sa.PrimaryKeyConstraint('id', name=op.f('chart_of_accounts_pkey'))
    )
    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_of_accounts_account_code'), ['account_code'], unique=True)

    op.drop_table('user_settings')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_setting_key'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
