"""Add accounting module

Revision ID: 510eb8214826
Revises: 
Create Date: 2026-01-25 21:25:52.773025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510eb8214826'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))  # Made nullable
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'journal_entries', ['journal_id'], ['id'])
        batch_op.create_foreign_key(None, 'chart_of_accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('account_id')
        batch_op.drop_column('journal_id')

    # ### end Alembic commands ###
