"""add vendor approvals and payments

Revision ID: d31109bc00e1
Revises: e1425b5224f9
Create Date: 2026-01-27 21:42:40.460405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31109bc00e1'
down_revision = 'e1425b5224f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ap_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'chart_of_accounts', ['ap_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ap_account_id')

    with op.batch_alter_table('vendor_bills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
