"""Add analytics fields to distributor

Revision ID: e1425b5224f9
Revises: 510eb8214826
Create Date: 2026-01-26 14:49:37.687159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1425b5224f9'
down_revision = '510eb8214826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_satisfaction_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('average_order_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_lifetime_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_order_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('order_frequency', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_column('order_frequency')
        batch_op.drop_column('last_order_date')
        batch_op.drop_column('total_lifetime_value')
        batch_op.drop_column('average_order_value')
        batch_op.drop_column('customer_satisfaction_score')
        batch_op.drop_column('loyalty_points')

    # ### end Alembic commands ###
